// This file is intentionally left empty.
// The Service Worker is auto-generated by the vite-plugin-pwa during the build process.
// Do not add manual caching logic here to avoid conflicts with the bundler.
